"""initial_schema

Revision ID: a5618c7dd872
Revises:
Create Date: 2025-11-21 20:46:18.692991

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5618c7dd872"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balances",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "coins",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("coin_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_type", sa.String(length=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("ai_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coin_id"],
            ["coins.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # 인덱스 생성
    op.create_index("idx_trades_coin_id", "trades", ["coin_id"])
    op.create_index("idx_trades_created_at", "trades", ["created_at"])
    op.create_index("idx_balances_created_at", "balances", ["created_at"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 인덱스 삭제
    op.drop_index("idx_balances_created_at", "balances")
    op.drop_index("idx_trades_created_at", "trades")
    op.drop_index("idx_trades_coin_id", "trades")
    # 테이블 삭제
    op.drop_table("trades")
    op.drop_table("coins")
    op.drop_table("balances")
    # ### end Alembic commands ###
